// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StashBankApplication.Model.Context;

#nullable disable

namespace StashBankApplication.Migrations
{
    [DbContext(typeof(MSSQLContext))]
    [Migration("20260302204252_FixCardColumns")]
    partial class FixCardColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StashBankApplication.Model.Account", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("bool")
                        .HasColumnName("active");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("date")
                        .HasColumnName("created_on");

                    b.Property<decimal>("funds")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("funds");

                    b.Property<string>("numeroconta")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasColumnName("name");

                    b.Property<long>("userid")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("id");

                    b.HasIndex("userid");

                    b.ToTable("account");
                });

            modelBuilder.Entity("StashBankApplication.Model.Card", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<decimal>("AvailableCredit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("available_credit");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("credit_limit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastUpgradeAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_upgrade_at");

                    b.Property<int>("Tier")
                        .HasColumnType("int")
                        .HasColumnName("tier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("date")
                        .HasColumnName("created_on");

                    b.HasKey("id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("card");
                });

            modelBuilder.Entity("StashBankApplication.Model.Transaction", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("accountid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("date")
                        .HasColumnName("created_on");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("type")
                        .HasColumnType("smallint");

                    b.Property<decimal>("value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("accountid");

                    b.ToTable("transaction");
                });

            modelBuilder.Entity("StashBankApplication.Model.Transfer", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("createdon")
                        .HasColumnType("date")
                        .HasColumnName("created_on");

                    b.Property<long>("id_account_from")
                        .HasColumnType("bigint");

                    b.Property<long>("id_account_to")
                        .HasColumnType("bigint");

                    b.Property<decimal>("value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.ToTable("transfer");
                });

            modelBuilder.Entity("StashBankApplication.Model.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("createdon")
                        .HasColumnType("date")
                        .HasColumnName("created_on");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("email");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("name");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("password");

                    b.HasKey("id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("StashBankApplication.Model.Account", b =>
                {
                    b.HasOne("StashBankApplication.Model.User", "user")
                        .WithMany()
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("StashBankApplication.Model.Card", b =>
                {
                    b.HasOne("StashBankApplication.Model.Account", "Account")
                        .WithOne("Card")
                        .HasForeignKey("StashBankApplication.Model.Card", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("StashBankApplication.Model.Transaction", b =>
                {
                    b.HasOne("StashBankApplication.Model.Account", "Account")
                        .WithMany()
                        .HasForeignKey("accountid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("StashBankApplication.Model.Account", b =>
                {
                    b.Navigation("Card");
                });
#pragma warning restore 612, 618
        }
    }
}
